const env = require("./env");

const SERVICES = {
  AUTH: env.AUTH_SERVICE_URL,
  USER: env.USER_SERVICE_URL,
  PROJECT: env.PROJECT_SERVICE_URL,
  NOTIFICATION: env.NOTIFICATION_SERVICE_URL,
  MEDIA: env.Media_SERVICE_URL,
  AI: env.AI_SERVICE_URL,
  REPORT: env.REPORT_SERVICE_URL,
  BILLING: env.BILLING_SERVICE_URL,
  SUBMISSION: env.SUBMISSION_SERVICE_URL,
};

module.exports = { SERVICES };
